<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'League\\ISO3166\\Exception\\DomainException' => $vendorDir . '/league/iso3166/src/Exception/DomainException.php',
    'League\\ISO3166\\Exception\\InvalidArgumentException' => $vendorDir . '/league/iso3166/src/Exception/InvalidArgumentException.php',
    'League\\ISO3166\\Exception\\OutOfBoundsException' => $vendorDir . '/league/iso3166/src/Exception/OutOfBoundsException.php',
    'League\\ISO3166\\Guards' => $vendorDir . '/league/iso3166/src/Guards.php',
    'League\\ISO3166\\ISO3166' => $vendorDir . '/league/iso3166/src/ISO3166.php',
    'League\\ISO3166\\ISO3166DataProvider' => $vendorDir . '/league/iso3166/src/ISO3166DataProvider.php',
    'League\\ISO3166\\ISO3166DataValidator' => $vendorDir . '/league/iso3166/src/ISO3166DataValidator.php',
    'PWall\\Client' => $vendorDir . '/lib/Client.php',
    'PWall\\Exception\\ExceptionInterface' => $vendorDir . '/lib/Exception/ExceptionInterface.php',
    'PWall\\Exception\\InvalidArgumentException' => $vendorDir . '/lib/Exception/InvalidArgumentException.php',
    'PWall\\Helper\\Constants' => $vendorDir . '/lib/Helper/Constants.php',
    'PWall\\Helper\\ProxyHelper' => $vendorDir . '/lib/Helper/ProxyHelper.php',
    'PWall\\Request' => $vendorDir . '/lib/Request.php',
    'PWall\\Response' => $vendorDir . '/lib/Response.php',
    'PWall\\SaleResponse' => $vendorDir . '/lib/SaleResponse.php',
    'PWall\\Utils\\Logger' => $vendorDir . '/lib/Utils/Logger.php',
);
