<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit784958e6477c40b8c05900cbaf08eda2
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PWall\\' => 6,
        ),
        'L' => 
        array (
            'League\\ISO3166\\' => 15,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PWall\\' => 
        array (
            0 => __DIR__ . '/..' . '/lib',
        ),
        'League\\ISO3166\\' => 
        array (
            0 => __DIR__ . '/..' . '/league/iso3166/src',
        ),
    );

    public static $classMap = array (
        'League\\ISO3166\\Exception\\DomainException' => __DIR__ . '/..' . '/league/iso3166/src/Exception/DomainException.php',
        'League\\ISO3166\\Exception\\InvalidArgumentException' => __DIR__ . '/..' . '/league/iso3166/src/Exception/InvalidArgumentException.php',
        'League\\ISO3166\\Exception\\OutOfBoundsException' => __DIR__ . '/..' . '/league/iso3166/src/Exception/OutOfBoundsException.php',
        'League\\ISO3166\\Guards' => __DIR__ . '/..' . '/league/iso3166/src/Guards.php',
        'League\\ISO3166\\ISO3166' => __DIR__ . '/..' . '/league/iso3166/src/ISO3166.php',
        'League\\ISO3166\\ISO3166DataProvider' => __DIR__ . '/..' . '/league/iso3166/src/ISO3166DataProvider.php',
        'League\\ISO3166\\ISO3166DataValidator' => __DIR__ . '/..' . '/league/iso3166/src/ISO3166DataValidator.php',
        'PWall\\Client' => __DIR__ . '/..' . '/lib/Client.php',
        'PWall\\Exception\\ExceptionInterface' => __DIR__ . '/..' . '/lib/Exception/ExceptionInterface.php',
        'PWall\\Exception\\InvalidArgumentException' => __DIR__ . '/..' . '/lib/Exception/InvalidArgumentException.php',
        'PWall\\Helper\\Constants' => __DIR__ . '/..' . '/lib/Helper/Constants.php',
        'PWall\\Helper\\ProxyHelper' => __DIR__ . '/..' . '/lib/Helper/ProxyHelper.php',
        'PWall\\Request' => __DIR__ . '/..' . '/lib/Request.php',
        'PWall\\Response' => __DIR__ . '/..' . '/lib/Response.php',
        'PWall\\SaleResponse' => __DIR__ . '/..' . '/lib/SaleResponse.php',
        'PWall\\Utils\\Logger' => __DIR__ . '/..' . '/lib/Utils/Logger.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit784958e6477c40b8c05900cbaf08eda2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit784958e6477c40b8c05900cbaf08eda2::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit784958e6477c40b8c05900cbaf08eda2::$classMap;

        }, null, ClassLoader::class);
    }
}
