<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'PWall\\' => array($vendorDir . '/lib'),
    'League\\ISO3166\\' => array($vendorDir . '/league/iso3166/src'),
);
